import {createClient} from '@supabase/supabase-js';
export const ready=()=>Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.SITE_URL);
export function fail(status,message){throw Object.assign(new Error(message),{status})}
export const response=(status,data,cookies=[])=>({statusCode:status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},multiValueHeaders:{'Set-Cookie':cookies},body:JSON.stringify(data)});
export function wrap(fn){return async event=>{try{return await fn(event)}catch(e){if(!e.status)console.error('Request failed:',e.name);return response(e.status||503,{error:e.status?e.message:'Serviço temporariamente indisponível. Tente novamente em instantes.'})}}}
export function requireSetup(){if(!ready())fail(503,'A loja está em preparação. O acesso será liberado em breve.')}
export function body(event){if(event.httpMethod!=='POST')fail(405,'Método não permitido.');if(event.headers.origin!==new URL(process.env.SITE_URL).origin)fail(403,'Origem não permitida.');if((event.body||'').length>12000)fail(413,'Requisição muito grande.');try{return JSON.parse(event.body||'{}')}catch{fail(400,'Dados inválidos.')}}
export const admin=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
export const anon=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
export function cookies(event){try{return Object.fromEntries((event.headers.cookie||'').split(';').filter(Boolean).map(c=>{const i=c.indexOf('=');return [c.slice(0,i).trim(),decodeURIComponent(c.slice(i+1))]}))}catch{return {}}}
export function sessionCookies(session){const attrs='; Path=/; HttpOnly; Secure; SameSite=Lax';return [`dtc_access=${encodeURIComponent(session?.access_token||'')}; Max-Age=${session?session.expires_in||3600:0}${attrs}`,`dtc_refresh=${encodeURIComponent(session?.refresh_token||'')}; Max-Age=${session?2592000:0}${attrs}`]}
export async function identity(event){requireSetup();const client=anon(),c=cookies(event);let {data,error}=c.dtc_access?await client.auth.getUser(c.dtc_access):{data:{user:null},error:true};let updated=[];let token=c.dtc_access;if(error&&c.dtc_refresh){const refreshed=await client.auth.refreshSession({refresh_token:c.dtc_refresh});if(!refreshed.error){data={user:refreshed.data.user};error=null;token=refreshed.data.session.access_token;updated=sessionCookies(refreshed.data.session)}}if(error||!data.user)fail(401,'Entre na sua conta para continuar.');return {user:data.user,cookies:updated,token}}
export async function mp(path,options={}){const res=await fetch('https://api.mercadopago.com'+path,{...options,headers:{Authorization:`Bearer ${process.env.MERCADO_PAGO_ACCESS_TOKEN}`,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(15000)});if(!res.ok)fail(502,'Não foi possível consultar o Mercado Pago. Tente novamente.');return res.json()}
export function checked(result){if(result.error)throw result.error;return result.data}
